#!/bin/bash

# Navigation
# ----------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."


# Network
# -------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then
    alias localip="ifconfig | \
                   grep 'inet addr' | \
                   grep -v '127.0.0.1' | \
                   cut -d: -f2 | \
                   cut -d' ' -f1"
elif [ "$os" == "mac" ]; then
    alias localip="ipconfig getifaddr en0"
fi


# Local server
# ------------

alias sstart="sudo apachectl start"
alias sstop="sudo apachectl stop"


# Git
# ---

alias ga="git add"
alias gst="git status"
alias gc="git commit -m"
alias gca="git commit -a -m"
alias gd="git diff"
alias gm="git merge --no-ff"
alias gpt="git push --tags"
alias gph="git push"
alias gpl="git pull"
alias grh="git reset --hard"
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -D"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gl="git log --pretty=format --graph --date=local"
alias gcd='cd "`git rev-parse --show-toplevel`"'


# Shorter Commands
# ----------------

alias e="vim"
alias g="git"
alias l="ls -CF"
alias ll="ls -alF"
alias la="ls -A"
alias m="man"
alias q="exit"
alias :q="exit"
alias rm="rm -rf"

# OS / OS distribution specific commands
if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then

    # Hide/Show desktop icons
    alias hidedesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons false"
    alias showdesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons true"

elif [ "$os" == "mac" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed
    alias emptytrash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"

    # Hide/Show desktop icons
    alias hidedesktopicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
    alias showdesktopicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

    # Hide/Show hidden files in Finder
    alias hidehiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
    alias showhiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

fi
