#!/bin/bash

# Navigation
# ----------

alias ~="cd ~"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cd..="cd .."


# Network
# -------

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then
    alias localip="ifconfig | \
                   grep 'inet addr' | \
                   grep -v '127.0.0.1' | \
                   cut -d: -f2 | \
                   cut -d' ' -f1"
elif [ "$os" == "mac" ]; then
    alias localip="ipconfig getifaddr en0"
fi


# Local server
# ------------

alias sstart="sudo apachectl start"
alias sstop="sudo apachectl stop"


# Brew services
# -------------

alias bsl="brew services list"
# brew services start <formula>
alias bsstart="brew services start"
# brew services stop <formula>
alias bsstop="brew services stop"


# Git
# ---

alias ga="git add"
alias gst="git status"
alias gc="git commit -m"
alias gca="git commit -a -m"
alias gd="git diff"
alias gdn="git diff --name-status"
alias gm="git merge --no-ff"
alias gph="git push"
alias gpt="git push --tags"
alias gpl="git pull"
alias grh="git reset --hard"
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -D"
alias gco="git checkout"
alias gcob="git checkout -b"
alias grp="git remote prune"
alias gss="git stash"
alias gsp="git stash pop"
alias gsl="git stash list"
alias gsd="git stash drop"
alias gl="git log --pretty=format --graph --date=local"
alias gln="gl --name-status"
alias gcd='cd "`git rev-parse --show-toplevel`"'

# add completion on git aliases
if type __git_complete > /dev/null 2>&1; then
  __git_complete gph _git_push
  __git_complete gpt _git_push --tags
  __git_complete gpl _git_pull
  __git_complete gco _git_checkout
  __git_complete gbd _git_branch -D
fi


# Docker
# ------

alias d="docker"
alias da="docker ps -a"
alias di="docker images"
alias dcon="docker container"
alias dima="docker image"
alias dvol="docker volume"
alias dnet="docker network"
alias dcbuild="docker-compose build"
alias dcup="docker-compose up"
alias dcupb="docker-compose up --build"
alias dcdown="docker-compose down"
alias dcrun="docker-compose run"
dsa() { docker stop $(docker ps -aq); }


# Rails
# -----

alias r="rails"
alias raisl="rails"
alias be="bundle exec"


# Shorter Commands
# ----------------

alias e="vim"
alias g="git"
alias gti="git"
alias l="ls -CF"
alias ll="ls -alF"
alias la="ls -A"
alias m="man"
alias q="exit"
alias :q="exit"
#alias rm="rm -rf"

# OS / OS distribution specific commands
if [[ "$os" == "linux" && "$distro" == "ubuntu" ]]; then

    # Hide/Show desktop icons
    alias hidedesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons false"
    alias showdesktopicons="gsettings set org.gnome.desktop.background show-desktop-icons true"

elif [ "$os" == "mac" ]; then

    # Empty the trash, the main HDD and on all mounted volumes
    # and clear Apple’s system logs to improve shell startup speed
    alias emptytrash="sudo rm -frv /Volumes/*/.Trashes && \
                      sudo rm -frv ~/.Trash &&
                      sudo rm -frv /private/var/log/asl/*.asl"

    # Hide/Show desktop icons
    alias hidedesktopicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
    alias showdesktopicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

    # Hide/Show hidden files in Finder
    alias hidehiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
    alias showhiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"

fi
