#!/bin/bash

# FUNCTIONS
# =========

source_bash_files() {
  local distro="" i="" tmp="" os=""
  local osname="$(uname -s)"

  declare -a files=(
    # "git-prompt.sh"
    "git-completion.bash"
    "aliases"
    "exports"
    "options"
    "prompt"
    # "bash.local"    # for local settings that are not under
                      # version control (e.g. git credentials)
  )

  # Some things are OS specific, deal with it
  if [ "$osname" == "Darwin" ]; then
    os="mac"
  elif [ "$osname" == "Linux" ]; then
    os="linux"

    # Get Linux distribution
    # (list of release: http://linuxmafia.com/faq/Admin/release-files.html)
    distro=$(check_linux_release "lsb-release" "ubuntu") ||
           $(check_linux_release "debian_version" "debian") ||
           $(check_linux_release "debian_release" "debian")
  else
    os="other"
  fi

  for i in ${!files[*]}; do
    tmp="$HOME/.dotfiles/bash/${files[$i]}"
    [ -r "$tmp" ] && source "$tmp"
  done
}


# MAIN
# ====

# Enable programmable completion features
# if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#     . /etc/bash_completion
# fi

if [[ $COLORTERM == gnome-* && $TERM == xterm ]] \
   && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

source_bash_files
unset source_bash_files
